version: '3.1'

services:

  db:
    image: postgres:latest
    ports:
      - '9999:9999'
    volumes:
      - ./data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 12345